### ISSUE TITLE
please merge qubes subfolder

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#19]
Could you please move [`/qubes/systemd/corridor-data.service.d/qubes.conf`](https://github.com/rustybird/corridor/blob/master/qubes/systemd/corridor-data.service.d/qubes.conf) directly into [`/qubes/systemd/corridor-data.service.d/qubes.conf`](https://github.com/rustybird/corridor/blob/master/systemd/corridor-data.service.in)? [Analogous for other similar files in `/qubes/systemd/` folder.)

Alternatively `/systemd/corridor-data.service.d/qubes.conf` would also be very nice.

* Would simplify the whole corridor package. (Less files, folders.)
* Would simplify the systemd service.
* Does no damage at any non-Qubes users having these settings.
 * Statements like `After=qubes-iptables.service` are simply ignored for non-Qubes users.
* Would simplify the makefile and packaging (#10).

-----

Also [`/qubes/corridor.d`](https://github.com/rustybird/corridor/tree/master/qubes/corridor.d) could be avoided and merged into the [`corridor.d`](https://github.com/rustybird/corridor/tree/master/corridor.d) if using the "if Qubes is detected" way.

```
# Setting this by default in Qubes only.
if command -v qubesdb-read >/dev/null 2>&1 ; then
   # Qubes specific config snippett
fi
```

**Comment by adrelanos** [comment]
Another argument for implementing this ticket. If corridor ends up in official Debian package sources...

* #10 
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829740

Then they would probably not use `make install-qubes` since that is irrelevant to plain Debian. Then the Debian repository version would not work for Qubes Debian templates, which would be a shame.

**Comment by rustybird** [comment]
I'd really rather not litter people's installations with unneeded code. Today it is Qubes stuff, tomorrow it might be OpenWRT, etc. And every line is a cognitive burden for an admin who wants to check out how things work.

(About the the install-qubes target: When dealing with bureaucracies, it often seems to me that if the application of a particular interpretation of a rule introduces negative externalities for no good reason, then it is best to just charitably reinterpret it so that it does not to apply to the specific case...)
